quoteconfig:
  quotes:
  - text: "Don't judge each day bu the harvest you reap but by the seeds that you plant."
    author: Robert Louis Stevenson
  - text: "The only thing necessary for the triumph of evil is for good men to do nothing."
    author: Edmund Burke
  - text: "Do not go where the path may lead, go instead where there is no path and leave a trail."
    author: Ralph Waldo Emerson
  - text: "Success is not final, failure is not fatal: it is the courage to continue that counts."
    author: Winston Churchill
  - text: "In three words I can sum up everything I've learned about life: it goes on."
    author: Robert Frost
  - text: "The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails."
    author: William Arthur Ward
  - text: "The only true wisdom is in knowing you know nothing."
    author: Socrates
  - text: "The supreme art of war is to subdue the enemy without fighting."
    author: Sun Tzu
  - text: "I have not failed. I've just found 10,000 ways that won't work."
    author: Thomas Edison